### PR TITLE
Remove hardcoded smarthop related fields DEV-1227

### PR DESCRIPTION
**Pull request by LucilleH**
## Summary
Remove hardcoded smarthop related fields. Is it safe to remove?

## How was it tested?
launchpad up

## Is this change backwards-compatible?
yes-ish

### CODE REVIEW

**Comment by ipince** [comment]
Hmmm we'd have to check if it'll affect Smarthop

**Comment by ipince** [comment]
I mean, this will definitely break Smarthop. It won't break it when merged, but it'll break it the next time they deploy...

**Review by mikeland86 — APPROVED** [review]

**Comment by mikeland86** [comment]
I think this is fine. @Lagoja can send them a slack message to let them know and we can tell them how to set up a custom URL?

**Comment by Lagoja** [comment]
Can you share what I need to send them over Slack?

**Comment by LucilleH** [comment]
Need to remove this from open-source. Merging.

**Comment by ipince** [comment]
Note: this is *not* backwards-compatible, because some public api in `pkg/jetcloud/jetgcp/auth.go` was being used.  I'll look into it.

**Pull request merged**
